# controller config for ros2 control
controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Left
    left_iiwa_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_impedance_controller:
      type: impedance_controller/ImpedanceController

    left_ets_state_broadcaster:
      type: external_torque_sensor_broadcaster/ExternalTorqueSensorBroadcaster

    # Right
    right_iiwa_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_impedance_controller:
      type: impedance_controller/ImpedanceController

    right_ets_state_broadcaster:
      type: external_torque_sensor_broadcaster/ExternalTorqueSensorBroadcaster

# ============================ Left ============================
left_iiwa_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - left_joint_a1
      - left_joint_a2
      - left_joint_a3
      - left_joint_a4
      - left_joint_a5
      - left_joint_a6
      - left_joint_a7

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

left_velocity_controller:
  ros__parameters:
    joints:
      - left_joint_a1
      - left_joint_a2
      - left_joint_a3
      - left_joint_a4
      - left_joint_a5
      - left_joint_a6
      - left_joint_a7

left_impedance_controller:
  ros__parameters:
    joints:
      - left_joint_a1
      - left_joint_a2
      - left_joint_a3
      - left_joint_a4
      - left_joint_a5
      - left_joint_a6
      - left_joint_a7
    stiffness: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
    damping: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

left_ets_state_broadcaster:
  ros__parameters:
    sensor_name: left_external_torque_sensor

# ============================ Right ============================
right_iiwa_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - right_joint_a1
      - right_joint_a2
      - right_joint_a3
      - right_joint_a4
      - right_joint_a5
      - right_joint_a6
      - right_joint_a7

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

right_velocity_controller:
  ros__parameters:
    joints:
      - right_joint_a1
      - right_joint_a2
      - right_joint_a3
      - right_joint_a4
      - right_joint_a5
      - right_joint_a6
      - right_joint_a7

right_impedance_controller:
  ros__parameters:
    joints:
      - right_joint_a1
      - right_joint_a2
      - right_joint_a3
      - right_joint_a4
      - right_joint_a5
      - right_joint_a6
      - right_joint_a7
    stiffness: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
    damping: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

right_ets_state_broadcaster:
  ros__parameters:
    sensor_name: right_external_torque_sensor
